kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-blob-production
  namespace: production
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-blob-production
  storageClassName: azureblob-nfs-premium