apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
  namespace: production
spec:
  provider: azure
  secretObjects:
    - secretName: app-secrets
      type: Opaque
      data:
        - objectName: db-user
          key: DB_USER
        - objectName: db-password
          key: DB_PASSWORD
        - objectName: db-name
          key: DB_NAME
        - objectName: db-host
          key: DB_HOST
        - objectName: jwt-secret
          key: JWT_SECRET
        - objectName: vue-app-backend-url
          key: VUE_APP_BACKEND_URL
    - secretName: ingress-tls-csi
      type: kubernetes.io/tls
      data:
        - objectName: emark-production
          key: tls.crt
        - objectName: emark-production
          key: tls.key
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 
    keyvaultName: 
    cloudName: ""
    objects: |
      array:
        - |
          objectName: db-user
          objectType: secret
        - |
          objectName: db-password
          objectType: secret
        - |
          objectName: db-name
          objectType: secret
        - |
          objectName: db-host
          objectType: secret
        - |
          objectName: jwt-secret
          objectType: secret
        - |
          objectName: vue-app-backend-url
          objectType: secret
        - |
          objectName: emark-production
          objectType: secret
    tenantId: 
